import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = await readFile(resolve(root, 'src/client.js'), 'utf8')
const css = await readFile(resolve(root, 'src/skin.css'), 'utf8')
const buddy = await readFile(resolve(root, 'assets/retro-buddy.svg'))
const buddyUrl = `data:image/svg+xml;base64,${buddy.toString('base64')}`

if (!source.includes('__QQ2007_CSS__') || !source.includes('__QQ2007_BUDDY_URL__')) {
  throw new Error('client source placeholders are missing')
}

const body = source
  .replace('__QQ2007_CSS__', JSON.stringify(css))
  .replace('__QQ2007_BUDDY_URL__', JSON.stringify(buddyUrl))
const output = `// Generated by scripts/build-client.mjs; edit src/client.js and src/skin.css.\nwindow.__ModuleLoader__.load({\n  id: "dsh-qq2007-skin",\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;\n${body.split('\n').map((line) => `    ${line}`).join('\n')}\n    return module.exports;\n  }\n});\n`

await writeFile(resolve(root, 'lib/client.js'), output, 'utf8')
console.log(JSON.stringify({
  moduleId: 'dsh-qq2007-skin',
  cssBytes: Buffer.byteLength(css),
  buddyBytes: buddy.length,
  clientBytes: Buffer.byteLength(output)
}))
